<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDrmbmvw\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDrmbmvw/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerDrmbmvw.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerDrmbmvw\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerDrmbmvw\appProdProjectContainer(array(
    'container.build_hash' => 'Drmbmvw',
    'container.build_id' => '390a0cdd',
    'container.build_time' => 1520345941,
));
