<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNtnf1wc\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNtnf1wc/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerNtnf1wc.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerNtnf1wc\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerNtnf1wc\appProdProjectContainer(array(
    'container.build_hash' => 'Ntnf1wc',
    'container.build_id' => '7264c320',
    'container.build_time' => 1520007311,
));
