<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2pluxut\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2pluxut/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2pluxut.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2pluxut\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container2pluxut\appDevDebugProjectContainer(array(
    'container.build_hash' => '2pluxut',
    'container.build_id' => 'b596ad00',
    'container.build_time' => 1519942649,
));
