<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2srorh2\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2srorh2/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2srorh2.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2srorh2\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container2srorh2\appDevDebugProjectContainer(array(
    'container.build_hash' => '2srorh2',
    'container.build_id' => '3fdfaf8b',
    'container.build_time' => 1520006484,
));
